SELECT * FROM CLIENTE;

/* Modelagem Basica - 
ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL-CARACTER(30)
TELEFONE-CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSO DE MODELAGEM */

/* FASE 1 E 2 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 3 DE DBA  / AD / */ 

MODELAGEM FISICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FISICA*/

CREATE DATABASE PROJETO;

/*CONECTANDO AO BANCO*/
USE PROJETO

/*CRIANDO A TABELA CLIENTES*/

CREATE TABLE LIVROS(
    NOME_DO_LIVRO VARCHAR(25),
    NOME_DO_AUTOR VARCHAR(30),
    SEXO VARCHAR(10),
    NUMERO_DE_PAGINAS  INT(5),
    NOME_DA_EDITORA VARCHAR(25),
    VALOR_DO_LIVRO FLOAT(10,2),
    ESTADO_UF_DA_EDITORA CHAR(2),
    ANO_PUBLICACAO INT(5)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DESCOBRINDO A ESTRUTURA DE UMA TABELA*/

DESC CLIENTE;

/* RENOMEANDO A TABELA*/

RENAME TABLE CLENTE TO CLIENTE;

/* tuplas = registros = linhas */

INSERT INTO LIVROS VALUES
('Cavaleiro Real',	'Ana Claudia',	'Feminino',	465	,'Atlas',	49.9,	'RJ',	'2009'),
('SQL para leigos',	'João Nunes',	'Masculino',	450,	'Addison',	98,	'SP',	'2018'),
('Receitas Caseiras',	'Celia Tavares', 'Feminino',	210,	'Atlas',	45,	'RJ',	'2008'),
('Pessoas Efetivas',	'Eduardo Santos',	'Masculino',	390,	'Beta',	78.99,	'RJ',	'2018'),
('Habitos Saudáveis',	'Eduardo Santos',	'Masculino',	630,	'Beta',	150.98,	'RJ',	'2019'),
('A Casa Marrom',	'Hermes Macedo',	'Masculino',	250,	'Bubba',	60,	'MG',	'2016'),
('Estacio Querido',	'Geraldo Francisco',	'Masculino',	310,	'Insignia',	100,	'ES',	'2015'),
('Pra sempre amigas',	'Leda Silva',	'Feminino',	510,	'Insignia',	78.98,	'ES',	'2011'),
('Copas Inesqueciveis',	'Marco Alcantara',	'Masculino',	200,	'Larson',	130.98,	'RS',	'2018'),
('O poder da mente',	'Clara Mafra',	'Feminino',	120,	'Continental',	56.58,	'SP',	'2017');


DROP TABLE IF EXISTS LIVROS;

    SELECT departamento, nome 
FROM FUNCIONARIOS
where departamento='roupas' or departamento='filmes'
group by departamento;

SELECT DEPARTAMENTO, count(*) from funcionarios
group by departamento;

SELECT departamento, nome, email,sexo 
FROM FUNCIONARIOS
where (departamento='lar' or departamento='filmes') and sexo='feminino'
;

SELECT nome,sexo,departamento 
FROM FUNCIONARIOS
where sexo='masculino' or departamento='jardim'
order by 2;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(30) UNIQUE,
    CPF VARCHAR(15) UNIQUE 
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES','COM','CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE NOME = 'CELIA';

SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, TIPO, NUMERO
FROM CLIENTE 
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT IDCLIENTE, EMAIL FROM CLIENTE, ENDERECO,TELEFONE
WHERE BAIRRO='CENTRO' AND ESTADO='RJ'
AND TIPO='CEL' AND NUMERO=NULL;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
       T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO='M';

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (12, 13,18,19);

^^^^PEGA UM DETERMINADO INTERVALO^^^^

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
       T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO='F';
